[project]
name = "idap-memory-issues"
version = "0.1.0"
description = "Debugging of memory issues identified in the IDAP ATLAS 200 Gbps challenge"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

alex = """
python examples/uproot_dask_memory_alex.py
"""

lindsey = """
python examples/dask_awkward_memory_lindsey.py
"""

[dependencies]
python = "==3.9.12"
uproot = ">=5.3.3,<5.4"
dask = ">=2024.4.2,<2024.5"
distributed = ">=2024.4.2,<2024.5"
dask-awkward = ">=2024.3.0,<2024.4"
jupyterlab = ">=4.1.6,<4.2"
notebook = ">=7.1.3,<7.2"

[pypi-dependencies]
memory-profiler = { version = "==0.61.0" }
