[project]
name = "idap-memory-issues"
version = "0.1.0"
description = "Debugging of memory issues identified in the IDAP ATLAS 200 Gbps challenge"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[tasks]

alex = """
python examples/uproot_dask_memory.py
"""

uproot-open = """
python examples/uproot_open.py
"""

lindsey = """
python examples/dask_awkward_memory.py
"""

memory-issue-uproot-dask = """
python examples/run_memory_issue_uproot_dask.py
"""

memory-issue-uproot = """
python examples/run_memory_issue_uproot.py
"""

[dependencies]
python = "==3.9.12"
uproot = ">=5.3.3,<5.4"
dask = ">=2024.4.2,<2024.5"
distributed = ">=2024.4.2,<2024.5"
dask-awkward = ">=2024.3.0,<2024.4"
jupyterlab = ">=4.1.6,<4.2"
notebook = ">=7.1.3,<7.2"
pyyaml = ">=6.0.1,<6.1"

[feature.mprof.dependencies]
matplotlib = ">=3.8.4,<3.9"

[feature.mprof.pypi-dependencies]
memory-profiler = { version = "==0.61.0" }

[feature.mprof.tasks]
mprof = """
mprof run examples/uproot_dask_memory.py && \
mprof plot --output figures/uproot_dask_memory_mprof.png
"""

[feature.memray.dependencies]
memray = ">=1.12.0,<1.13"

[feature.memray.tasks]
memray-uproot-dask = """
memray run --output output/uproot_dask.bin examples/uproot_dask_memory.py && \
memray flamegraph output/uproot_dask.bin
"""

[feature.scalene.dependencies]
scalene = ">=1.5.39,<1.6"

[feature.scalene.tasks]
scalene-uproot-dask = """
scalene --outfile output/uproot_dask_scalene.html examples/uproot_dask_memory.py
"""

[environments]
# all environments include the default feature
mprof = ["mprof"]
memray = ["memray"]
scalene = ["scalene"]
